version: '3.9'

services:
  backend:
    build:
      context: /home/ec2-user/shareLife_back
      dockerfile: Dockerfile
    command: npm run start:dev
    container_name: sharelife_backend
    env_file:
      - .env
    ports:
      - '3000:3000'
    restart: always
