version: '3.9' # optionnel, mais conseill√© de mettre la version

services:
  backend:
    build:
      context: /home/ec2-user/shareLife_back
      dockerfile: Dockerfile
    command: npm run start:dev
    container_name: sharelife_backend
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: /home/ec2-user/shareLife_back
        target: /app
        bind:
          create_host_path: true
      - type: volume
        target: /app/node_modules
        volume: {}
    restart: always
