version: '3.9' # optionnel, mais conseillé de mettre la version

services:
  backend:
    build: .
    container_name: sharelife_backend
    restart: always
    ports:
      - '3000:3000'
    environment:
      JWT_SECRET: supersecret
    env_file:
      - .env
    volumes:
      - .:/app # monte ton code local dans le container
      - /app/node_modules # pour éviter de réécraser node_modules
    command: npm run start:dev # lance Nest avec hot reload

volumes:
  db_data:
