name: CI/CD Backend

on:
  push:
    branches: [deploiement]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Installer Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3. Build l'image Docker
      - name: Build Docker image
        run: |
          docker build -t backend:latest ./

      # 4. SSH sur ton EC2 et mettre Ã  jour le conteneur
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/shareLife_back
            docker-compose pull
            docker-compose build backend
            docker-compose up -d backend
